---
- name: Configuring apache2
  hosts: all
  tasks:
    - name: Install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
      notify: Check apache response
    - name: Edit the index.html file
      copy:
        content: "Welcome to IntelliQIT"
        dest: /var/www/html/index.html
      notify: Restart apache2
  handlers:
    - name: Restart apache2
      service:
        name: apache2
        state: restarted
    - name: Check apache response
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.92.36
        - http://172.31.86.20
        - http://172.31.89.180
...
